services:
  sparksweb-website:
    image: ghcr.io/sparkswebdevelopment/website:prod
    container_name: sparksweb-website
    restart: always
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true