services:
    sparksweb:
        image: ghcr.io/sparkswebdevelopment/website:prod
        container_name: sparksweb-website
        restart: always
        ports:
            - "3000:3000"
        networks:
            - proxy-net

networks:
    proxy-net:
        external: true